FROM openjdk:15

ADD startup.sh /startup.sh

RUN apt-get install -y unzip 
 
RUN curl https://languagetool.org/download/LanguageTool-4.9.zip -o lt.zip && \
    unzip lt.zip

RUN chmod +x /startup.sh

EXPOSE 8081

CMD /startup.sh