stages:
  - build
  - push 
<<<<<<< HEAD
  
=======

>>>>>>> ba3e0e6 (Squashed commit)
before_script:
  - docker info

build_image: 
  stage: build
<<<<<<< HEAD
  tags:
    - stokwell
    - local
  only:
    - master
  script:
    - docker build -t registry.gitlab.com/stokwell1/dv-rails:latest .

push_image: 
  stage: push
  tags:
    - shell
  only:
    - master
  before_script: 
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
  script: 
    - docker push registry.gitlab.com/stokwell1/dv-rails:latest






  
=======
  tags: 
    - docker
    - digitalocean
    - remote
  script:
    - docker build -t registry.gitlab.com/stokwell1/dv-rails:1.0 .

push_image: 
  stage: push
  tags: 
    - docker
    - digitalocean
    - remote
  before_script: 
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
  script: 
    - docker push registry.gitlab.com/stokwell1/dv-rails:1.0
>>>>>>> ba3e0e6 (Squashed commit)
