version: '3.4'

services:
  app:
<<<<<<< HEAD
    build:
      context: .
      dockerfile: Dockerfile
=======
    image: stokwell/dv:3.0
    # build:
    #   context: .
    #   dockerfile: Dockerfile
>>>>>>> ba3e0e6 (Squashed commit)
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
<<<<<<< HEAD
    command: ["bundle", "exec", "rails", "server", "-p", "3000", "-b", "0.0.0.0"]
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    # env_file: .env
    environment:
      RAILS_ENV: development
=======
    # command: ["bundle", "exec", "rails", "server", "-p", "3000", "-b", "0.0.0.0"]
    volumes:
      - .:/app
      # - gem_cache:/usr/local/bundle/gems
      # - node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: 1
>>>>>>> ba3e0e6 (Squashed commit)
      DATABASE_USER: postgres
      DATABASE_HOST: postgres
      REDIS_HOST: redis
      REDIS_URL: redis://redis:6379/
<<<<<<< HEAD
=======
      SECRET_KEY_BASE: '940c32722b7ee37d6aeb95e1c647d6460b5f47b6b5aae975e7d9dde1557fc7f01531884aa7aad9c2c2a06ce2760f06fd85d11fd9ea7168d42b5345da12731e26'
>>>>>>> ba3e0e6 (Squashed commit)
    entrypoint: ./entrypoints/docker-entrypoint.sh

  postgres:
    image: postgres:12.1
    volumes:
      - db_data:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
<<<<<<< HEAD
    image: redis:5.0.7
=======
    image: redis:6
>>>>>>> ba3e0e6 (Squashed commit)
    command: redis-server --databases 8196
    ports:
      - 127.0.0.1:6379:6379

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app
      - postgres
      - redis
    volumes:
      - .:/app
<<<<<<< HEAD
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development
    entrypoint: ./entrypoints/sidekiq-entrypoint.sh

=======
      # - gem_cache:/usr/local/bundle/gems
      # - node_modules:/app/node_modules
    # env_file: .env.production
    environment:
      RAILS_ENV: production
      REDIS_HOST: redis
      REDIS_URL: redis://redis:6379/
      SECRET_KEY_BASE: '940c32722b7ee37d6aeb95e1c647d6460b5f47b6b5aae975e7d9dde1557fc7f01531884aa7aad9c2c2a06ce2760f06fd85d11fd9ea7168d42b5345da12731e26'
    entrypoint: ./entrypoints/sidekiq-entrypoint.sh

  languagetool:
    # image: lg:latest
    build:
      context: ./docker_containers/docker-languagetool
      dockerfile: Dockerfile
    depends_on:
      - app
    ports:
      - 8010:8010

>>>>>>> ba3e0e6 (Squashed commit)
volumes:
  gem_cache:
  db_data:
  node_modules:
