apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-volume
  labels:
    type: local 
    app: postgres
spec:
  storageClassName: ''
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"