apiVersion: apps/v1
kind: Deployment
metadata:
  name: dv-sidekiq-deployment
  labels: 
    app: dv-sidekiq
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dv-sidekiq
  template:
    metadata:
      labels:
        app: dv-sidekiq
    spec:
      containers:
      - name: dv-sidekiqb
        # image: stokwell/daily-vocabulary-sidekiq:0.1.12
<<<<<<< HEAD
        image: stokwell/dv-rails:0.2.3
=======
        # image: stokwell/dv-rails:0.2.4
        image: stokwell/dv-rails:0.3.8
>>>>>>> ba3e0e6 (Squashed commit)
        command: ['bundle', 'exec', 'sidekiq']
        env:
        - name: DATABASE_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: password
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: host
        # - name: REDIS_HOST
        #   valueFrom:
        #     configMapKeyRef:
        #       name: redis-configmap
        #       key: host
        # - name: REDIS_PORT
        #   valueFrom:
        #     configMapKeyRef:
        #       name: redis-configmap
        #       key: port
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: redis-configmap
              key: redis_url

