default: &default
  adapter: postgresql
  encoding: utf-8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: 'dv_rails_user'
  password: 'dv_rails_password'
  host: postgres

development:
  <<: *default
  database: dv_rails_development

test:
  <<: *default
  database: dv_rails_test

production:
  <<: *default
  database: dv_rails_production
